mdm_proj:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: poc #optional catalog name if you are using Unity Catalog]
      schema: test # Required
      host: https://dbc-310a2e81-0c22.cloud.databricks.com # Required
      http_path: /sql/1.0/warehouses/71cd50649b08224c # Required
      token: dapid24744b3c7e1b0a75eb1f1e374989ce9 # Required Personal Access Token (PAT) if using token-based authentication
      threads: 1  # Optional, default 1